# Generated by Django 5.1.3 on 2024-12-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('role', models.CharField(default='user', max_length=10, verbose_name='Роль')),
            ],
        ),
    ]
