# Generated by Django 5.1.3 on 2024-12-08 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Устройство')),
                ('hall', models.CharField(max_length=255, verbose_name='Зал')),
                ('booking_time', models.TimeField()),
                ('hours', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.authuser')),
            ],
        ),
    ]
